=head1 PERL+OPENMP WIKI

Welcome. The main thrust of this project is language exploration. In particular,
explore how to best leverage OpenMP (which is available on C<gcc> since 2005!)
within Perl.

=head1 CURRENT RESEACH GOAL

=over 4

=item Explore approaches to exposing OpenMP in C<Tie::*> interfaces for basic Perl structures (SCALAR, HASH, ARRAY)

=item Useful keyword implementations that do stuff using OpenMP

=item Other things .. (list it)

=back

=head1 REPOS OF EXPERIMENTAL THINGS

=over 4

=item Pure fiction, nothing else: L<https://github.com/oodler577/p5-fan-fiction>

Literally just exploring how to write threaded code. It probably doesn't make sense and it probably doesn't compile.

=item 
