=head1 USE WIKI LINK ONLY

this is not a real repo, only using it to get the I<wiki> tab.

=head1 USAGE

To edit, do the C<git> thing:

    git clone https://github.com/Perl-OpenMP/wiki.wiki.git

To view,

Press C<Wiki> tab above or, click:

https://github.com/Perl-OpenMP/wiki/wiki

=head1 CONTRIBUTORS

Yes, please.
